### PR TITLE
Updating the readme with some basic description and the commands for basic usage

### PR DESCRIPTION
**Pull request by pvandervelde**
Updated the readme to provide some basic description of the commands needed to use the library.

references #1

### CODE REVIEW

**Comment by enricobellocchio** [comment]
Hi @pvandervelde ! thank you for your support!
I've tried to launch the experiment in this way:

- in one terminal i've launched the ignition code with:
        **ros2 launch zinger_ignition ignition.launch.py rviz:=true world:=room_with_walls_1 use_sim_time:=true**

- in one terminal i've launched the robot description with:
         **ros2 launch zinger_description robot_description.launch.py use_sim_time:=true**

- in one terminal 've launched the slam node with:
          **ros2 launch zinger_nav slam.launch.py use_sim_time:=true** 

- and finally in the last terminal i've launched the navigation with:
          **ros2 launch zinger_nav nav2.launch.py use_sim_time:=true**

unfortunelly in the slam terminal i have a stream of the following message:

[async_slam_toolbox_node-1] [INFO] [1715092105.551186423] [slam_toolbox]: Message Filter dropping message: frame 'link_sensor_lidar_rplidar_front' at time 799.720 for reason 'discarding message because the queue is full'

meanwhile in the navigation terminal i have the following message:

[controller_server-1] [INFO] [1715092744.469632819] [local_costmap.local_costmap]: Timed out waiting for transform from base_footprint to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist

and no map is showing up.. can you give me any suggestion? thank you very much!

**Comment by pvandervelde** [comment]
I just checked and it looks like this might be caused by not having the swerve controller running. I've updated the readme on this branch to reflect that. In short you'll need to grab the [zinger_swerve_controller](https://github.com/pvandervelde/zinger_swerve_controller) package and run that in a separate terminal with:

    ros2 launch zinger_swerve_controller swerve_controller.launch.py use_sim_time:=true

Once that is running there will be a transform between the robot base and the odometry frame, which is what the SLAM module needs to calculate the transform from the Lidar unit to the world map.

**Comment by pvandervelde** [comment]
Also you don't need to run the description package itself, if you run the ignition package then that will pull in the description package and publish the robot description etc. 
So you'll need:

- one terminal with the ignition package running
- one terminal with the swerve controller running
- one terminal with the SLAM tools running
- one terminal with the Nav tools running

Then further I find it useful to run foxglove to get all the data out in a sensible way.

**Comment by enricobellocchio** [comment]
OK now it's working! thank you very much for your support, for the suggestions and for sharing your works!

**Comment by pvandervelde** [comment]
Awesome. Is the new readme looking ok? Is there anything else you are missing. If so let me know and I'll update. If you think it's all good, then I'll merge this PR.

**Comment by enricobellocchio** [comment]
yes, maybe you can add the suggestion to change the fixed frame on the global options of rviz from "base_footprint" to "map" to be able to correctly publish nav2 goals. Thank you again for your support!

**Pull request merged**
